### ISSUE TITLE
Decryption during download

### ISSUE THREAD

**Issue by nishabe** [RNCryptor/RNCryptor-objc#10]
Hello Rob,
Thank you very much for your effort in creating this brilliant library and spending time on maintaining it.
Could you please clarify the below question?
I have a bunch of audio files which are encrypted and stored in the server. The key is bundled with the client application. 
Is it possible to use RNCryptor to decrypt the files during download, so that I can start playback before the file is completely downloaded? 
I have gone through [this discussion](https://groups.google.com/forum/#!topic/rncryptor/KuW5GpVtn9w) and as I understand, it is not supported, as of now.

Please share your thoughts on this.

**Comment by rnapier** [comment]
Decrypting during download is not a problem, but there are several problems in your use case.

The first, and most important, is that it's not clear what you're hoping to achieve. If you bundle the key in the application, then anyone who has the application on a jailbroken device can decrypt the files. If they don't have a jailbroken device, then TLS (with a properly pinned cert) is just as good as RNCryptor, and much simpler.

But putting that aside, decrypting during download is not a problem. I assume you're using an `AVPlayer`? If so, then you'll want to build an `NSURLProtocol` to handle decryption during its download. I wrote about `NSURLProtocol` in [Drop-in Offline Caching for UIWebView (and NSURLProtocol)](http://robnapier.net/offline-uiwebview-nsurlprotocol), and that provides the skeleton of a protocol for you. If you google `NSURLProtocol` you'll find several other writers on the subject. It's no problem to hook an async decryptor into a protocol (see Async and Streams in the docs for the basics of how you manage data that shows up in chunks off a stream).

The basic answer is it's not a problem to do, but probably more trouble than it's worth. You're better off just using `AVPlayer` over TLS, [pinning your certificate,](https://github.com/rnapier/RNPinnedCertValidator), and using BasicAuth to "authenticate" your app. (BasicAuth here is next to useless, but it's exactly equivalent to the protection you're getting from RNCryptor if you put the key in binary.)
