### ISSUE TITLE
Is there any way to accurately deduce the size of the file after it is encrypted without actually encrypting?

### ISSUE THREAD

**Issue by maxisme** [RNCryptor/RNCryptor-objc#12]
I can get the `fileSize` of a file at a path, like this:
```
NSData* file = [NSData dataWithContentsOfFile:path];
float fileSize = [file length];
```

Is there anyway to get the size of the file after it has been encrypted without actually encrypting it like this:

```
NSData *data = [NSData dataWithContentsOfFile:path];
NSData *encrypted_data = [RNCryptor encryptData:data password:password];
```

**Comment by rnapier** [comment]
For full details, see the [spec](https://github.com/RNCryptor/RNCryptor-Spec/blob/master/RNCryptor-Spec-v3.md).

Your plaintext will first be padded to a multiple of 16 bytes. If it is already a multiple of 16 bytes, an additional 16 bytes will be added. Thus a 0-length (empty) plaintext is 16 bytes. A 10 byte plaintext is 16 bytes. A 15 byte plaintext is 16 bytes. A 16 byte plaintext is 32 bytes. Etc.

There is then 66 bytes of overhead.

In total, a zero byte plaintext will be 82 bytes of cipher. 16 bytes of plaintext will 98 bytes of cipher, etc.

**Comment by maxisme** [comment]
Thank you! Sorry to send to both repos!

**Comment by rnapier** [comment]
Not a problem. What's the use case here? If it seems common enough, I can easily add a method that will tell you this (so it's always correct).

**Comment by maxisme** [comment]
Building a file transfer application in which the user will be limited to a specific amount of upload size (don't want to have to punish them for encrypting the file). Yeah I think that would be useful. I basically authorise the user with a php script before they upload the file so that they do not need to upload the file to realise they have exceeded the limit.

Currently writing a jsfiddle to send you to make sure I understand what you mean! P.S thank you so much for all your hard work on this repo. It is brilliant.

**Comment by maxisme** [comment]
haha that took me a long time: https://jsfiddle.net/wy6an0ge/ is this the idea?

**Comment by rnapier** [comment]
Looks about right.

**Comment by maxisme** [comment]
Tested and works!
```
-(int)bytesToEncrypted:(int)bytes{
    int overhead = 66;
    
    if (bytes == 0) {
        return 16 + overhead;
    }
    
    int remainder = bytes % 16;
    if (remainder == 0) {
        return bytes + 16 + overhead;
    }
    
    return bytes + 16 - remainder + overhead;
}
```
