### ISSUE TITLE
What is the corresponding openssl-algorithm for kRNCryptorAES256Settings?

### ISSUE THREAD

**Issue by itinance** [RNCryptor/RNCryptor-objc#13]
I tried successfully your example code for working with streams. Using this library i can encrypt and decrypt files with the setting **kRNCryptorAES256Settings**.

But what setting is necessary to decrypt files, that were encrypted for instance with the "aes-256-cbc"-algorithm? 

When i encrypt a file in the terminal with

`openssl enc -aes-256-cbc -in m1010.jpg -out m1010.data`

and decrypt this using RNDecryptor, the output is totally different and wrong.

Is there a list of corresponding settings available according to this library and those that are available in openssl? Thank you very much in advance

**Comment by rnapier** [comment]
Please see the [FAQ](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format).

**Comment by itinance** [comment]
Ok, thx for fast reply @rnapier! Any ideas or proposals how to encrypt files on a linux server that are compatible to RNCryptor and could be decrypted with this lib on iOS and Android-Devices? The RNCrypto-php repo uses openssl itself that isn't compatible any more (I've already tried out)

**Comment by rnapier** [comment]
The PHP version should be compatible. I suspect you're using it incorrectly. The most common mistake is applying Base64 encoding and failing to apply Base64 decoding. The bytes that come out of the encryptor must be exactly the bytes that go into the decryptor.

**Comment by rnapier** [comment]
(PHP has a habit of being sloopy with data and randomly turning it into strings. This creates a lot of confusion.)

**Comment by itinance** [comment]
It's the library that converts binary data into base64: https://github.com/RNCryptor/RNCryptor-php/blob/master/src/RNCryptor/Encryptor.php#L95

Will try tomorrow again without this encoding

**Comment by itinance** [comment]
Alright. Without the base64encode in https://github.com/RNCryptor/RNCryptor-php/blob/master/src/RNCryptor/Encryptor.php#L95 its working fine to enrypt files on php side and to decrypt it with objc
Will submit a PR in RNCryptor-php in order to provide a base64-less encryption
