### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by inPhilly** [RNCryptor/RNCryptor-objc#14]
How can this be used with Carthage for an Objective-C project?

**Comment by rnapier** [comment]
Did you run into trouble just adding `github "RNCryptor/RNCryptor-objc"` to your Cartfile? I don't test package managers very much, but it should just work.

**Comment by inPhilly** [comment]
I added it but it produces different results than the other frameworks. I had to remove it so I can't tell you exactly what happens. I seriously have spent countless hours trying to integrate this into an iOS app. Would you possibly consider adding instructions?

**Comment by inPhilly** [comment]
I personally can use Carthage (but not CocoaPods), but I would love if you could share a step by step installation method independent of a third party installer. This is killing me. I have spent over 30 hours trying to get this into my app. Granted, I am inexperienced. But I could really use the help. I can't even compile anymore and one of my frameworks depends on this.

**Comment by rnapier** [comment]
I apologize for not getting back. To build manually, just copy the files directly into your project in Xcode. That's the easiest way to use it. There's no need for package management.
