### ISSUE TITLE
Xcode 9 & iOS 11 beta issue 

### ISSUE THREAD

**Issue by Venkat1128** [RNCryptor/RNCryptor-objc#19]
Hi ,
I have issue in RNCryptor.m file 
RNCryptor.m:61:12: Conflicting types for 'SecRandomCopyBytes'
I am using pod 'RNCryptor-objc' .
My App is crashing becasue fo this issue .
Please let me know when do we have fix for this.

Thanks,
Venkat

**Comment by Weever** [comment]
I have this problem too

//extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));

you can do this temporary, but hope author fix this issue

**Comment by ikzjfr0** [comment]
i have this problem too.

**Comment by rnapier** [comment]
Which version of RNCryptor are you using? 3.0.5 should have fixed this. It wraps that definition in a check for OS X <= 10.6.

**Comment by Venkat1128** [comment]
Thanks for response.
Yes, i have updated the pod and issue were fixed.

Much appreciated.

Thanks,
Venkat

**Comment by codestrummer29** [comment]
Which version do I need to use to fix this issue?  
I am currently using 2.2 
I tried 3.0.5 but it says 
- `RNCryptor (~> 3.0.5)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `RNCryptor (~> 3.0.5)`.

**Comment by rnapier** [comment]
@codestrummer29 I don't understand the question. 3.0.5 is the version that addresses this, and is the latest version on [cocoapods.org](https://cocoapods.org/pods/RNCryptor-objc). I would expect that you haven't updated your repositories (spec source?), but I don't know very much about Cocoapods.

**Comment by ghost** [comment]
Hi Everyone,

I have the same issues and unfortunately my developer abandon me with this project. Can anyone guide me step-by-step how to update to 3.0.5 ? Thank you

**Comment by rnapier** [comment]
@adrianevs That depends on exactly how you're using RNCryptor. If you're just using CocoaPods, then it depends on whether your Podfile requests a specific version (2.2), in which case you should change it to 3.0.5. Either way, you should run `pod update RNCryptor` and checkin your changes. As far as step-by-step instructions, it's very dependent on how your project is laid out, and is probably beyond what can easily be done in an Issue comment.

If you need assistance, I do small-scale consulting and would be happy to discuss. You can reach me at robnapier@gmail.com.
