### ISSUE TITLE
Can I user like this

### ISSUE THREAD

**Issue by loumzy** [RNCryptor/RNCryptor-objc#23]
Can I use like this, I just need simple use and less params? But It is not work correct for me. The 'base64Encrypt' is not right.
```
const RNCryptorSettings kRNCryptorAES128Settings = {
    .algorithm = kCCAlgorithmAES128,
    .blockSize = kCCBlockSizeAES128,
    .IVSize = kCCBlockSizeAES128,
    .options = kCCOptionPKCS7Padding
};

    NSData *data = [@"Data" dataUsingEncoding:NSUTF8StringEncoding];
    NSError *error;
    NSData *encryptedData = [RNEncryptor encryptData:data
                                        withSettings:kRNCryptorAES128Settings
                                       encryptionKey:[@"15hcxttc3gas63st" dataUsingEncoding:NSUTF8StringEncoding]
                                             HMACKey:NULL
                                                  IV:[@"1234567890123456" dataUsingEncoding:NSUTF8StringEncoding]
                                               error:&error];
    
    NSString *base64Encrypt = [encryptedData base64EncodedStringWithOptions:0];

```

**Comment by rnapier** [comment]
The above code doesn't make sense. Passing `NULL` as the HMACKey is clearly broken. This looks like you're trying to use RNCryptor for something other than the RNCryptor format. See the [FAQ](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format) about that. RNCryptor is not a general-purpose crypto library; it encodes a very specific format, designed to be secure. (What the code above is trying to do is very insecure, and the kind of format I built RNCryptor to replace.)

Using this method is an advanced usage for special cases. General usage is as described in the docs, using a password:

```
NSData *data = [@"Data" dataUsingEncoding:NSUTF8StringEncoding];
NSError *error;
NSData *encryptedData = [RNEncryptor encryptData:data
                                   	withSettings:kRNCryptorAES256Settings
                                          password:aPassword
                                             error:&error];
```

You should not use the key API unless you know how to correctly generate encryption and HMAC keys by hand and need the performance on repeated encryption using the same keys.
