### ISSUE TITLE
How do I decrypt using a third party AES-CBC decryptor?

### ISSUE THREAD

**Issue by syardumi** [RNCryptor/RNCryptor-objc#28]
So far, I've been able to encrypt and decrypt nicely in iOS using this RNCryptor lib. But, the trouble comes when decryption needs to happen outside of the iOS playground. Here's what I've tried so far:

**password**
asdfasdfasdfasdf

**plaintext**
{ "stuff": "here" }

```
NSData *encryptedData = [RNEncryptor encryptData:[@"{ \"stuff\": \"here\" }" dataUsingEncoding:NSUTF8StringEncoding]
                                            withSettings:kRNCryptorAES256Settings
                                                password:@"asdfasdfasdfasdf"
                                                   error:&error];

```

Using password and plaintext in the RNCryptor-objc encryption library I get:
**cipher hex**
03 01 59 fe 9e 5f f2 c2 05 58 ab 85 29 c5 a5 6f ad 27 5e e0 e8 a1 af f2 1f e4 e9 61 8b 25 44 1b ba ee e4 71 ef 95 e9 16 3b 59 53 a2 74 d9 23 00 57 1f a6 4f b9 ff 86 8d e6 ae 76 5a 4a 15 eb b8 d0 b4 bb 54 50 d0 76 3d 45 1c b5 c3 41 1f 1d 09 b8 97 6a ba 91 44 2e 1f f4 54 42 44 ce 59 b0 cc 0b 14 64 30

Break up cipher hex into parts below according to this format (https://github.com/RNCryptor/RNCryptor-Spec/blob/master/RNCryptor-Spec-v3.md):
——————
**version (1 byte)**
03

**options (1 byte)**
01

**encryption salt (8 bytes)**
59 fe 9e 5f f2 c2 05 58

**HMAC salt (8 bytes)**
ab 85 29 c5 a5 6f ad 27

**IV (16 bytes)**
5e e0 e8 a1 af f2 1f e4 e9 61 8b 25 44 1b ba ee

**ciphertext (x bytes)**
e4 71 ef 95 e9 16 3b 59 53 a2 74 d9 23 00 57 1f a6 4f b9 ff 86 8d e6 ae 76 5a 4a 15 eb b8 d0 b4 bb 54 

**HMAC (32 bytes)**
50 d0 76 3d 45 1c b5 c3 41 1f 1d 09 b8 97 6a ba 91 44 2e 1f f4 54 42 44 ce 59 b0 cc 0b 14 64 30

—————————

Using PBKDF2 function with 32 byte length, 10k iterations, SHA-1, and encryption salt (above), generate an encryption key (http://anandam.name/pbkdf2/):

**encryption key** 
d57972b596a34a18e201d2f6a301424dcf269ccc757e07f91765935af491aa68

Then, decrypt to plaintext using ciphertext, IV, and encryption key using third party AES decryption function (http://extranet.cryptomathic.com/aescalc/index):
**Decrypted plaintext in hex**
AD409D9EFE09B360B2B905A82C41CE67BD7D106095742BFF055891F8CE1D524EAB6EDC147F565796ED7AAF6F4E8A024A

Convert from hex to ASCII:
**Decrypted plaintext in ASCII** 
@ žþ	³`²¹¨,AÎg½}`•t+ÿX‘øÎRN«nÜ VW–íz¯oNŠJ

-------------------------

Obviously, I'm missing something here, but I'm not sure what it is. Am I missing padding on the cipher hex and/or HMAC and/or ciphertext? Am I not generating the encryption key correctly? 

Thanks for any help you can provide,
Steve Y

**Comment by rnapier** [comment]
The PBKDF2 site you reference seems to treat the salt as an ASCII (maybe UTF8) string. How are you providing the raw bytes to it?

**Comment by syardumi** [comment]
Ah, that could be it! I'm providing the hex value to it instead. Do you have a reference for a PBKDF2 function that uses hex for the salt input?

**Comment by rnapier** [comment]
Do you mean something like https://asecuritysite.com/encryption/PBKDF2z?

**Comment by syardumi** [comment]
Yes. But have you tried to Generate Hash on this calculator? I'm getting an HTTP 500 error from jQuery when I do.

**Comment by rnapier** [comment]
Yeah; worked fine.
![screen shot 2018-07-05 at 12 53 32 pm](https://user-images.githubusercontent.com/429858/42336709-79ea3bbc-8052-11e8-86ed-a33209e34a14.png)

(The "auto-detect if the value is an ASCII string or hex" worries me a lot; you'll have to play with it to make sure it's really reading it as a hex string. I really hate security interfaces that try to auto-detect things.)

**Comment by rnapier** [comment]
All this said, I don't understand what you're trying to do. Are you writing a new RNCryptor implementation?

**Comment by syardumi** [comment]
No. My use case is that I have strings encrypted locally on an iOS device, our client wants to be able to pull them off the device, and decrypt them if they get "stuck" there (not able to transmit over HTTPS because of offline, locked device, bug, etc.)

I see what I did wrong with the calculator: the Salt hex needs spaces in between each set, and I was entering it as a hex string with none.

That said, it looks like the key generated from that site is the same one I got from the first site I tried.

**Comment by rnapier** [comment]
I don't know that adding spaces is correct. I just copied your hex. (this is why I said I hate auto-detection; I don't know whether it detects correctly.)

If you want to decrypt this off-device, I'd just use one of the various RNCryptor implementations to build a small tool to do that in the language of your choice (it may already exist). Let me know and I can walk you through that (or if you need something specialized, I'm happy to discuss consulting).

RNCryptor is available in a lot of languages, and it's pretty easy to build a commandline tool to decrypt things if you need that. I think I have one built already, or pretty close to one.

**Comment by syardumi** [comment]
Ok. I did toss around the idea of building a tool with a different language implementation, but we are trying to avoid adding a lot of hours to our project. 

Do you know of any tools out there using RNCryptor already (even if they are pay-to-use)?

Thanks again for helping me work through this case.

**Comment by rnapier** [comment]
What kind of tool is most useful here? A command-line tool? A hosted web page? A native Mac or Windows app? They're all pretty easy to build. If you want me to build it, we can talk cost. I wouldn't expect it to be very much, especially if it's sponsored open source (my rates are much lower when I can release the source code publicly).

Take a look at the [organization](https://github.com/RNCryptor) to see all the existing implementations.  For an example of a really simple Mac command-line tool that does this already see [`rncrypt`](https://github.com/RNCryptor/RNCryptor-objc/blob/master/rncrypt/main.m). It's really sloppy and low-feature, but it shows how its done. Building a similar thing in the language of your choice should be pretty straightforward. Certainly much simpler than trying to decrypt this stuff by hand with random web tools.

**Comment by syardumi** [comment]
Well, I believe a hosted web page is the most useful. While the client could get along with a command line tool, it's not ideal in case their technical team changes. And, a native Mac or Windows or hybrid (Electron-based) one could take more time. 

I see now in the documentation of the PHP implementation that it's directly "interchangeable" with the objective-C implementation which is perfect for what I'm trying to accomplish. I'm going to see if I can take a run at a quick and dirty site for decrypting RNCryptor-encrypted base64 strings.

If we decide we need something more robust, I'll hit you up again to talk about building something and cost. Thanks, and great work on this library - it's extremely useful and the many language implementations are a great addition too.
