### ISSUE TITLE
Synchronous methods hang on invalid key

### ISSUE THREAD

**Issue by rcdilorenzo** [RNCryptor/RNCryptor-objc#29]
Hey @rnapier,

I'm trying to refresh an old project by different developers who employed this library. However, it always seems to hang in the `synchronousResultForCryptor:data:error:` method. The semaphore there never seems to get signaled because the handler never seems to get called at all (i.e. https://github.com/RNCryptor/RNCryptor-objc/blob/master/RNCryptor/RNCryptor.m#L99-L122).

Am I missing some sort of dependency or configuration? I tried both with the old version originally in the project as well as the latest version here. I've spent several hours trying to figure this out and am really hoping you might have some ideas.

(For integration, I've tried the original grab-the-source-and-stick-it-in as well as Carthage. I noticed the `Security` framework is listed in the pod spec but assumed that would be automatically imported where a project generally needs it.)

Thanks in advance for your time in considering my little problem. 😄 

P.S. I think I met you at a CocoaConf perhaps four or five years ago when you gave a talk on CoreText. I'm a native of Raleigh myself. 👍

**Comment by rnapier** [comment]
Do you have an example of this? Take a look at the [`rncrypt`](https://github.com/RNCryptor/RNCryptor-objc/tree/master/rncrypt) command-line example of this. I'm not seeing it hang.

**Comment by rcdilorenzo** [comment]
So, apparently, the previous owners of the project I'm reviving from the ashes decided to use this as the encryption key and HMAC for AES256 algorithm (for the unit tests):
```
NSData *dummyKey = [@"ABC" dataUsingEncoding:NSUTF8StringEncoding];
```

Once I discovered this problem, I wanted make it clear why I chose a particular value (as well as fix the "hanging" issue when the key is < 32 bytes). Fortunately, `@"This string is exactly 32 bytes."` is 32 characters and therefore translates to 32 bytes when using an ASCII-encoding. Therefore, the following will make this work AND help the next guy who comes in to read the code.

```
NSData *dummyKey = [@"This string is exactly 32 bytes." dataUsingEncoding:NSASCIIStringEncoding];
```

I thought it might be helpful in case others run into this indefinite hang.

**Comment by rnapier** [comment]
If the synchronous methods are hanging when the key is the wrong length, that's a bug. You should get an error, not a hang. I'll dig into that. Thanks.

(Of course you should never, ever create keys from strings like this; I wouldn't even unit test this way. But that doesn't change the fact that it's an RNCryptor bug.)

**Comment by rcdilorenzo** [comment]
Sure. That seems reasonable. I just wasn't sure how much time was being invested. Thanks for being a good OSS leader! 👍

**Comment by keyasu** [comment]
pod 'RNCryptor', '~> 3.0.1'
Xcode 10.0   
MacOS 10.14 
在这个文件中 #import "RNCryptor.h"
line 61   extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));

error message Conflicting types for 'SecRandomCopyBytes'

Pods/RNCryptor/RNCryptor/RNCryptor.m:61:12: Conflicting types for 'SecRandomCopyBytes'

**Comment by rnapier** [comment]
@HyBoard I'm not clear how this comment relates to the issue. You're running an out-of-date version of RNCryptor. 3.0.6 includes fixes for this issue.
