### ISSUE TITLE
Decrypt NSString

### ISSUE THREAD

**Issue by stephenkopylov** [RNCryptor/RNCryptor-objc#31]
Hello!
I Have a aes256-string, generated with this site: https://encode-decode.com/aes256-encrypt-online/
How to decrypt it with this library?

**Comment by rnapier** [comment]
https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format

Note that I'm happy to implement custom formats on a consulting basis. The particular site you've linked to is a very insecure format, however.
