### ISSUE TITLE
Error compiling for arm64

### ISSUE THREAD

**Issue by n3x7plorer** [RNCryptor/RNCryptor-objc#33]
The compiler tells me "Symbols not found for architecture arm64"

  "_OBJC_CLASS_$_RNDecryptor", referenced from:                                                                                  
      objc-class-ref                                                                             
  "_OBJC_CLASS_$_RNEncryptor", referenced from:                                                                                  
      objc-class-ref                                                                                
  "_kRNCryptorAES256Settings", referenced from:

**Comment by rnapier** [comment]
This generally would mean you're not linking RNCryptor into your app. How are you building it?
