### ISSUE TITLE
RNCryptor compatibility iOS 13

### ISSUE THREAD

**Issue by ghost** [RNCryptor/RNCryptor-objc#34]
Hello there,

Is there anyone who managed to use RNCryptor on an iOS 13 device ? if so what's the compatible version ?

**Comment by rnapier** [comment]
What problems are you seeing?

**Comment by SalouaSaksik** [comment]
________________________________
De : Rob Napier <notifications@github.com>
Envoyé : jeudi 11 juillet 2019 14:39
À : RNCryptor/RNCryptor-objc
Cc : SalouaSaksik; Author
Objet : Re: [RNCryptor/RNCryptor-objc] RNCryptor compatibility iOS 13 (#34)


What problems are you seeing?

**Comment by ghost** [comment]
It's working with other devices except the ones on iOS 13
<img width="871" alt="Capture d’écran 2019-07-12 à 09 33 25" src="https://user-images.githubusercontent.com/34394903/61114108-ec1b4700-a48f-11e9-972d-98213ca13f49.png">

**Comment by rnapier** [comment]
This looks like a problem with your CocoaPods setup. It's indicating a circular dependency from RNCryptor to Pods-AF_Press. But RNCryptor has no dependencies in its podspec (and certainly not something like Pods-AF_Press, which I assume is your project). I'd make sure that your cocoapods binary is up to date and re-run `pod install`. If that doesn't work, I'd build a small standalone project to try to reproduce this. I suspect it's a configuration problem in your main project.
