### ISSUE TITLE
Fortify security issue RNCryptor.m

### ISSUE THREAD

**Issue by usmaanirfan** [RNCryptor/RNCryptor-objc#36]
Hi,

We are getting fortify security issue in function + (NSData *)randomDataOfLength:(size_t)length on below line 
if (&SecRandomCopyBytes != NULL) {

**Description :** 

This expression will always be non-null because it references a function pointer rather than the return value of the function.

Example 1: The following conditional will never fire. The predicate getChunk == NULL will always be false because getChunk is the name of a function defined in the program.

if (getChunk == NULL)
return ERR;

Thanks,
Usman

**Comment by rnapier** [comment]
Fortify is incorrect (also, this is not a security issue). SecRandomCopyBytes will be NULL when RNCryptor is built for OS X 10.6, which is supported. In that case RNCryptor falls back to using RN_SecRandomCopyBytes instead. You will need to reconfigure your scan, or work with the vendor to fix their bug.

See the `extern` declaration at https://github.com/RNCryptor/RNCryptor-objc/blob/master/RNCryptor/RNCryptor.m#L64.

For more information on this technique, see [Frameworks and Weak Linking](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/WeakLinking.html) in Apple's Framework Programming Guide.
