### ISSUE TITLE
Code Correctness

### ISSUE THREAD

**Issue by SanjeevPantAri** [RNCryptor/RNCryptor-objc#37]
Hi
In the file RNEncryptor.m  we have a security issue for code correctness.The snippet where issue is the method:
 (NSData *)randomDataOfLength:(size_t)length
{
  NSMutableData *data = [NSMutableData dataWithLength:length];

  int result;
  if (&SecRandomCopyBytes != NULL) {
    result = SecRandomCopyBytes(NULL, length, data.mutableBytes);
  }
Description: The issue is raised for &SecRandomCopyBytes i.e Because it is missing trailing parentheses, the expression on line 386 in RNCryptor.m refers to the value of a function pointer rather than the return value of the function.
Please suggest if the conecern is valid or not.

**Comment by rnapier** [comment]
I believe this is an exact duplicate of #36. Please let me know if you believe there is more to it. Fortify is incorrect.
