### ISSUE TITLE
RNCryptor-objc GCM support

### ISSUE THREAD

**Issue by harishios** [RNCryptor/RNCryptor-objc#38]
Does RNCryptor-objc support GCM encryption? Fortify reports security issues for AES CBC.

**Comment by rnapier** [comment]
RNCryptor is a specific format, built on AES-CBC. It is not a general purpose cryptographic library. CBC is a secure mode if used correctly. Fortify is warning you that it is possible to misuse CBC. In particular, it’s probably warning you that CBC is unauthenticated. RNCryptor properly adds HMAC authentication. GCM is a very nice mode, but it would not change the security of the format, only break compatibility with the many existing RNCryptor implementations.
