### ISSUE TITLE
Encrypt an NSDictionary

### ISSUE THREAD

**Issue by calaforrai** [RNCryptor/RNCryptor-objc#42]
Hello, is there a way to encrypt an NSDictionary ?? thank for help @rnapier

**Comment by rnapier** [comment]
First convert your NSDictionary into bytes using whatever scheme you like (JSON, Property Lists, Protobuf, CSV, TLV, whatever is useful to you). Then encrypt the bytes. Encryption algorithms work on a stream of bytes. They don't care where the bytes come from or what they represent.

https://github.com/RNCryptor/RNCryptor#how-do-i-encryptdecrypt-a-string
