### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by raf-wtag** [RNCryptor/RNCryptor-objc#44]
How can I import this using SPM in a objc project? Seems like Package.swift file is missing

**Comment by rnapier** [comment]
Typically you should not. See https://github.com/RNCryptor/RNCryptor for the Swift version of this package. (Let me know if there's a particular reason you're trying to mix the old ObjC code with SPM, and we can take a look.)

**Comment by raf-wtag** [comment]
Actually I've used [RNCryptor-objc](https://github.com/RNCryptor/RNCryptor-objc) as I'm using this library in Objective-C extension and header files. But If I want to use https://github.com/RNCryptor/RNCryptor then I need to update the Objective-C usage. Thats why I was looking for SPM support for this
