### ISSUE TITLE
[RNEncryptor encryptData: withSettings:kRNCryptorAES256Settings password: error: ] - too many use of this method crash the app!

### ISSUE THREAD

**Issue by naderlavasani** [RNCryptor/RNCryptor-objc#6]
Hi,

"If you can,you test this issue first !"

when i using "encryptData" many time,app opens too many mach port('top' command show me open ports - #PRTS field) - when open ports go over 4000 app crashed!

**Comment by rnapier** [comment]
Which `encryptData` method are you calling? Are you calling it many times in parallel, or serially? Please post sample code that demonstrates the problem.

**Comment by naderlavasani** [comment]
Sorry for my delay

I created a method :

```
-(NSString *)encodeString:(NSString *)stringForEncoding {

    NSData * data = [stringForEncoding dataUsingEncoding:NSUTF8StringEncoding];

    NSError * error = nil;

    NSData * encryptedData = [RNEncryptor encryptData:data withSettings:kRNCryptorAES256Settings password:@"password" error:&error];

    NSString * base64String = [encryptedData base64EncodedStringWithOptions:nil];


    return base64String;
}
```

I created a timer/runloop in main function for executing another method every 10 second.that method, used above method for encrypting a string,so above method executed every 10 second.

**Comment by naderlavasani** [comment]
Mr.Napier, did you check my response?

**Comment by rnapier** [comment]
Can you build a small project that shows this problem and post it on GitHub? I haven't been able to reproduce this so far. I set the timer a lot faster (0.1s) but have no trouble encrypting >4000 times in a program. Are you sure it's actually related to encryption and not something else you're doing?
