### ISSUE TITLE
Open encrypted file without decrypted local copy

### ISSUE THREAD

**Issue by S2V** [RNCryptor/RNCryptor-objc#7]
Hi. @rnapier thank you for a job. I have a question. In my application I use `UIWebVIew` to view files (except images). `UIWebVIew` required data or link to the file. Data - not suitable for files can be quite large - so I can use `NSOutputStream` for decrypt - but in this case will need to create a local copy of the decrypted file (in a temp dir). Is there an alternative way, do not make copies of decrypted files?

**Comment by rnapier** [comment]
Use `NSURLProtocol` to create a shim layer that performs decryption for the `UIWebView`. See http://nshipster.com/nsurlprotocol/ and http://nshipster.com/nsurlprotocol/ for introductions to that. See https://github.com/rnapier/RNCachingURLProtocol for a very simple custom `NSURLProtocol` that performs caching. You can pull the caching out and replace it with decryption.

**Comment by S2V** [comment]
@rnapier - thx you, I should try this solution.
