### ISSUE TITLE
'RNCryptor.h' file not found

### ISSUE THREAD

**Issue by uthiel** [RNCryptor/RNCryptor-objc#9]
I try to use RNCryptor in my app like so:

**In my project:**
Cartfile: `github "RNCryptor/RNCryptor-objc"`
` carthage update RNCryptor-objc`
Add framework to "General / Linked frameworks and libraries"

**In a class file:**
`#import <RNCryptor/RNCryptor.h>`

**When trying to build:**
`While building module 'RNCryptor' imported from /Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Shared/TSCryptoKeys.m:11:
In file included from <module-includes>:1:
In file included from /Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Carthage/Build/iOS/RNCryptor.framework/Headers/RNCryptor iOS.h:22:
/Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Carthage/Build/iOS/RNCryptor.framework/PrivateHeaders/RNCryptorEngine.h:29:9: fatal error: 'RNCryptor.h' file not found
#import "RNCryptor.h"
        ^
1 error generated.`

What am I doing wrong?

**Comment by uthiel** [comment]
I found that `CLANG_ENABLE_MODULES = NO` solves the problem. But this can't be the proper solution, right?

**Comment by rnapier** [comment]
I don't really know how Carthage imports this kind of file (RNCryptor is
really designed to just be dropped directly into the project without
requiring package management; I provide package manager files for it
because they're requested, but I don't have any projects that use them). I
would assume you should be using `@import RNCryptor` rather than `#import
<RNCryptor/RNCryptor.h>`.

**Comment by uthiel** [comment]
Using `@import RNCryptor` results in one additional error to the one above

> While building module 'RNCryptor' imported from /Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Shared/TSCryptoKeys.m:11:
In file included from <module-includes>:1:
/Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Carthage/Build/iOS/RNCryptor.framework/Headers/RNCryptor iOS.h:22:9: error: include of non-modular header inside framework module 'RNCryptor' [-Werror,-Wnon-modular-include-in-framework-module]
#import <RNCryptor/RNCryptorEngine.h>
        ^
While building module 'RNCryptor' imported from /Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Shared/TSCryptoKeys.m:11:
In file included from <module-includes>:1:
In file included from /Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Carthage/Build/iOS/RNCryptor.framework/Headers/RNCryptor iOS.h:22:
/Users/udo/Documents/Xcode-Projects/aktiv/Tresor/Carthage/Build/iOS/RNCryptor.framework/PrivateHeaders/RNCryptorEngine.h:29:9: fatal error: 'RNCryptor.h' file not found

**Comment by uthiel** [comment]
> RNCryptor is really designed to just be dropped directly into the project without requiring package management;

Well I guess it's a matter of personal preferences, I like to treat external libraries as 'immutable', and therefore I don't want to include them into my project workspace, the same as I don't want to drop the UIKit source into my project (if I had access to it).
Additionally, using a package manager simplifies code update, not sure what to do when you update the code here at github and I'd just dropped in the files. Manually download, unzip and re-compile?

**Comment by rnapier** [comment]
Not saying you shouldn't use a package manager. I just don't really know what Carthage wants. I'm happy to accept PRs that make it compatible.

(And yes, at the beginning of every major release, I exactly "manually download, unzip, and re-compile" all my vendor packages. Most of the time it takes about 20 minutes, and I don't have to fight with package managers. Not saying others have to do that, but it works very well in all my projects.)

**Comment by uthiel** [comment]
Well disabling modules does work around the error I'm getting, not ideal but also not the end of the world, at least as long as I don't need modules in my project. Hence I'm closing this, thanks for your time and effort Rob, it is very much appreciated.
